export default {
    labelMessages: {},
    threadMessages: {},
    latestThreadMessageTime: {},
    labelNextPageTokens: {},
    labelLastPageTokens: [],
    token: "",
    currentUser: null,
    currentUserProfile: null,
    googleAuth: {},
    sessionExpiration: null,
    currentPage: 1,
    currentFolder: "INBOX",
    attachments: {},
    viewFolder: "Inbox",
    totalMessages: "0",
    draftIdsArray: [],
    userEmail: "",
    userName: "",
    tutorialUser: false,
}